* Why Emacs?
  Dotfiles-Indy May 23, 2020

* Abstract
  What's the deal with Emacs? I thought Vim was better anyway? Why
  should I switch from Visual Studio Code? Emacs is weird.

  Let's take a look at some demos to see what makes Emacs unique and
  highlight how it has inspired the software we use everyday.

  Featuring:
  - Buffers
  - Marks
  - Dired
  - TRAMP
  - Customize
  - Cool stuff

* Talk
** Buffers
   - Jump to recent files
   - Stop worrying about tabs and projects
   - Enjoy context-free and distraction-less editing

** Marks
   - Text selection with the keyboard
   - Popping the mark

** Dired
   - Move files (dwim)
   - Bulk rename (wdired)
   - Subdirectories (=i=, =C-u k=)

   #+BEGIN_SRC text
     /tmp/foobar
     ├── a
     ├── b
     ├── bar
     ├── baz
     ├── c
     └── foo
         ├── x
         └── y

     3 directories, 5 files
   #+END_SRC

** TRAMP

** Customize
   - =M-x describe-key RET M-;=
   - =M-x describe-variable RET scroll-bar-mode=
   - =M-x describe-function RET browse-url-at-point=
   - =M-x list-faces-display=

** Shell-command-on-region (cool stuff)
   Using =M-x shell-command-on-region= (=M-|=, =C-u M-|=)

   #+BEGIN_SRC sql
     cat ~/bin/pagila

     select city from (
       select distinct 1 + trunc(random() * 600)::integer as id
       from generate_series(1, 600) nums
     ) rand
       join city on city_id = id limit 10

     cities = [
       "Klerksdorp",
       "Balurghat",
       "Bergamo",
       "Mysore",
       "Tonghae",
       "Korolev",
       "Lancaster",
       "Kisumu",
       "Pune",
       "Uruapan",
       ]
   #+END_SRC
